@php
    $nombre = trim($registro->titulo ?: 'Nombre sin registrar');
    $iniciales = collect(preg_split('/\s+/', $nombre))->take(2)->map(fn ($parte) => mb_substr($parte, 0, 1))->implode('');
    $fechaRegistro = $registro->fecha ? \Illuminate\Support\Carbon::parse($registro->fecha)->locale('es')->translatedFormat('d M Y · H:i') : 'Sin fecha';
    $urlRegistro = $tab === 'preparacion'
        ? ($visibilidadNavegacion->puedeVerRuta('admin.admisiones.preadmisiones') ? route('admin.admisiones.preadmisiones', ['solicitud' => $registro->cod_preadmision ?: $registro->codigo, 'estado' => 'APROBADA']) : null)
        : ($registro->cod_residente && $visibilidadNavegacion->puedeVerRuta('admin.administracion.residentes.show') ? route('admin.administracion.residentes.show', $registro->cod_residente) : null);
    $resumenRegistro = ['nombre' => $nombre, 'codigo' => $registro->codigo, 'documento' => $registro->documento ?: 'Sin registrar',
        'etapa' => $tab === 'preparacion' ? 'Por formalizar' : 'Formalizada', 'fecha' => $fechaRegistro, 'estado' => str_replace('_', ' ', $registro->estado),
        'habitacion' => $registro->habitacion ?: 'Sin asignación registrada', 'cama' => $registro->cama ?: 'Sin asignación registrada',
        'url' => $urlRegistro, 'accion' => $tab === 'preparacion' ? 'Preparar ingreso' : 'Ver residente'];
@endphp
@if($modo === 'tabla')
    <tr><td><div class="rm-admissions-person"><span aria-hidden="true">{{ $iniciales }}</span><div><button type="button" @click="abrirResumen(@js($resumenRegistro), $el)" aria-label="Ver resumen de {{ $nombre }}">{{ $nombre }}</button><small>{{ $registro->codigo }}</small></div></div></td><td>{{ $registro->documento ?: 'Sin registrar' }}</td><td><span>{{ $registro->habitacion ?: 'Por asignar' }}</span><small>{{ $registro->cama ?: 'Sin cama registrada' }}</small></td><td>{{ $fechaRegistro }}</td><td><x-ui.status-badge :estado="$registro->estado" /></td><td><div class="rm-admissions-actions"><button type="button" @click="abrirResumen(@js($resumenRegistro), $el)" aria-label="Ver resumen de {{ $nombre }}" title="Ver resumen"><i class="ph-bold ph-identification-card" aria-hidden="true"></i></button>@if($urlRegistro)<a wire:navigate href="{{ $urlRegistro }}" aria-label="{{ $resumenRegistro['accion'] }}: {{ $nombre }}"><span>{{ $resumenRegistro['accion'] }}</span><i class="ph-bold ph-arrow-up-right" aria-hidden="true"></i></a>@endif</div></td></tr>
@else
    <article class="rm-admissions-record" role="listitem"><div class="rm-admissions-person"><span aria-hidden="true">{{ $iniciales }}</span><div><button type="button" @click="abrirResumen(@js($resumenRegistro), $el)" aria-label="Ver resumen de {{ $nombre }}">{{ $nombre }}</button><small>{{ $registro->codigo }}</small></div></div><div class="rm-admissions-record__facts"><p><i class="ph-bold ph-identification-card" aria-hidden="true"></i><span>{{ $registro->documento ? 'CI '.$registro->documento : 'Documento sin registrar' }}</span></p><p><i class="ph-bold ph-bed" aria-hidden="true"></i><span>{{ $registro->habitacion ?: 'Habitación por asignar' }} · {{ $registro->cama ?: 'Cama por asignar' }}</span></p><p><i class="ph-bold ph-calendar-blank" aria-hidden="true"></i><span>{{ $fechaRegistro }}</span></p></div><div class="rm-admissions-record__status"><x-ui.status-badge :estado="$registro->estado" /><small>{{ $resumenRegistro['etapa'] }}</small></div><div class="rm-admissions-actions"><button type="button" @click="abrirResumen(@js($resumenRegistro), $el)" aria-label="Ver resumen de {{ $nombre }}" title="Ver resumen"><i class="ph-bold ph-identification-card" aria-hidden="true"></i></button>@if($urlRegistro)<a wire:navigate href="{{ $urlRegistro }}" aria-label="{{ $resumenRegistro['accion'] }}: {{ $nombre }}"><span>{{ $resumenRegistro['accion'] }}</span><i class="ph-bold ph-arrow-up-right" aria-hidden="true"></i></a>@endif</div></article>
@endif
