@php $cerrar = route($rutaExplorador, $parametros); @endphp
<div class="rm-modal-shell rm-building-detail fixed inset-0 flex items-center justify-center p-4 is-open" x-show="!gestionAbierta" x-trap.inert.noscroll="!gestionAbierta" x-init="$nextTick(() => $refs.cerrar.focus())" x-on:keydown.escape.window="if (!gestionAbierta) window.location.assign(@js($cerrar))" role="dialog" aria-modal="true" aria-labelledby="espacio-detalle-titulo">
    <a href="{{ $cerrar }}" class="rm-modal-shell__overlay" tabindex="-1" aria-label="Cerrar detalle"></a>
    <section class="rm-modal-panel relative"><header class="rm-modal-header"><div><span class="rm-residents-eyebrow">{{ $detalle->habitacion }} · {{ filled($detalle->piso) ? 'Piso '.$detalle->piso : 'Piso sin registrar' }}</span><h2 id="espacio-detalle-titulo"><i class="ph-bold ph-bed" aria-hidden="true"></i> {{ $detalle->codigo }}</h2><span class="rm-building-status is-{{ $detalle->estado_mapa }}">{{ $estados[$detalle->estado_mapa][0] }}</span></div><a href="{{ $cerrar }}" x-ref="cerrar" class="rm-btn-icon" aria-label="Cerrar ficha de cama"><i class="ph-bold ph-x" aria-hidden="true"></i></a></header>
        <div class="rm-modal-body"><dl class="rm-residents-bed-modal__data"><div><dt>Tipo de cama</dt><dd>{{ $detalle->tipo ?: 'Sin registrar' }}</dd></div><div><dt>Estado registrado de cama</dt><dd>{{ $detalle->estado }}</dd></div><div><dt>Habitación / capacidad</dt><dd>{{ $detalle->habitacion }} · {{ $detalle->capacidad }} plazas</dd></div><div><dt>Estado de habitación</dt><dd>{{ $detalle->estado_habitacion }}</dd></div></dl>
            <section class="rm-building-occupant"><i class="ph-bold {{ $estados[$detalle->estado_mapa][1] }}" aria-hidden="true"></i><div><h3>{{ $detalle->ocupante ?: ($detalle->estado_mapa === 'ocupado' ? 'Ocupación activa registrada' : 'Sin ocupante actual') }}</h3><p>@if($detalle->fecha_hora_asignacion)Desde {{ \Carbon\Carbon::parse($detalle->fecha_hora_asignacion)->format('d/m/Y H:i') }} · {{ (int) max(0, \Carbon\Carbon::parse($detalle->fecha_hora_asignacion)->diffInDays(now())) }} días transcurridos.@else{{ $detalle->estado_mapa === 'disponible' ? 'Esta cama puede utilizarse al formalizar un ingreso o registrar un traslado.' : 'La cama o habitación no está habilitada para asignar.' }}@endif</p>@if($detalle->cod_admision && $verPersonas)<small>{{ $origenOcupacion }} Admisión {{ $detalle->cod_admision }}.</small>@endif</div></section>
            <section class="rm-building-notes"><h3><i class="ph-bold ph-notepad" aria-hidden="true"></i> Características y observaciones</h3><dl><div><dt>Cama</dt><dd>{{ $detalle->observacion ?: 'Sin observaciones registradas.' }}</dd></div><div><dt>Habitación</dt><dd>{{ $detalle->observacion_habitacion ?: 'Sin observaciones registradas.' }}</dd></div></dl></section>
            @if($verPersonas)<section class="rm-building-timeline"><h3><i class="ph-bold ph-clock-counter-clockwise" aria-hidden="true"></i> Trayectoria de esta cama</h3><p>Últimas 12 ocupaciones registradas; las liberaciones conservan su motivo.</p>@forelse($historial as $evento)<article><span class="rm-building-timeline__dot" aria-hidden="true"></span><div><strong>{{ $evento->estado }}</strong><time>{{ \Carbon\Carbon::parse($evento->fecha_hora_asignacion)->format('d/m/Y H:i') }} → {{ $evento->fecha_hora_liberacion ? \Carbon\Carbon::parse($evento->fecha_hora_liberacion)->format('d/m/Y H:i') : (in_array($evento->estado, ['ACTIVA', 'ACTIVO'], true) ? 'Vigente' : 'Fecha de liberación sin registrar') }}</time><small>{{ $evento->origen }}</small><p>{{ $evento->motivo_liberacion ?: (in_array($evento->estado, ['ACTIVA', 'ACTIVO'], true) ? 'La ocupación permanece activa; la cama no está disponible.' : 'Motivo de liberación sin registrar.') }}</p></div></article>@empty<p>Sin ocupaciones anteriores registradas.</p>@endforelse</section>@endif
        </div><footer class="rm-modal-footer"><a href="{{ $cerrar }}" class="rm-btn-secondary">Volver a {{ $esOcupacion ? 'ocupación' : 'habitaciones' }}</a>@if(!$esOcupacion)@can('camas.editar')<button type="button" class="rm-btn-primary" @click="gestionAbierta = true; $dispatch('editar-cama', {codCama: @js($detalle->cod_cama)})"><i class="ph-bold ph-pencil-simple" aria-hidden="true"></i> Editar cama</button>@endcan @elseif($detalle->cod_residente && $verPersonas)<a href="{{ route('admin.administracion.residentes', ['residente' => $detalle->cod_residente, 'vista' => 'camas']) }}" class="rm-btn-primary"><i class="ph-bold ph-identification-card" aria-hidden="true"></i> Ver residente y alojamiento</a>@elseif($esOcupacion && $detalle->estado_mapa === 'disponible')@if($verPersonas)@can('ocupaciones_cama.gestionar')<button type="button" class="rm-btn-primary" @click="gestionAbierta = true; $dispatch('elegir-residente-para-cama', {codCama: @js($detalle->cod_cama)})"><i class="ph-bold ph-plus" aria-hidden="true"></i> Elegir residente</button>@endcan @endif @if($visibilidadNavegacion->puedeVerRuta('admin.administracion.admisiones'))<a wire:navigate href="{{ route('admin.administracion.admisiones', ['tab' => 'preparacion']) }}" class="rm-btn-primary"><i class="ph-bold ph-user-plus" aria-hidden="true"></i> Preparar ingreso</a>@endif @endif</footer>
    </section>
</div>
