<x-sistema-layout>
@inject('visibilidadNavegacion', 'App\Backend\Modulos\Identidad\Servicios\VisibilidadNavegacion')
@php
    $estados = ['disponible' => ['Disponible', 'ph-bed', 'Lista para ingreso o traslado'], 'ocupado' => ['Ocupada', 'ph-user-circle', 'Con ocupación activa registrada'], 'no_habilitado' => ['No habilitada', 'ph-lock-key', 'Fuera de disponibilidad para asignar']];
    $parametros = array_filter(array_replace($filtros, ['vista' => $vista, 'por_pagina' => $porPagina]), fn ($valor, $clave) => filled($valor) && $clave !== 'cama', ARRAY_FILTER_USE_BOTH);
    $enlace = fn (array $cambios = []) => route('admin.administracion.habitaciones', array_filter(array_replace($parametros, array_key_exists('cama', $cambios) ? $cambios : ['page' => null] + $cambios), fn ($valor) => filled($valor)));
    $filtrosActivos = collect(['search' => 'Búsqueda', 'piso' => 'Piso', 'cod_habitacion' => 'Habitación', 'disponibilidad' => 'Disponibilidad', 'estado' => 'Estado registrado'])->filter(fn ($titulo, $clave) => filled($filtros[$clave] ?? ''));
    $porcentaje = $resumen['total'] ? round($resumen['ocupado'] / $resumen['total'] * 100) : 0;
    $totalFisico = max(1, $resumen['total']);
    $paginador = $habitaciones ?? $camas;
@endphp
<div class="rm-residents rm-building" x-data="rmHabitaciones()" :aria-busy="loading" x-on:livewire:navigated.window="loading = false" x-on:scroll.window="ocultarVistaPrevia()" x-on:resize.window="ocultarVistaPrevia()" x-on:keydown.escape.window="ocultarVistaPrevia()">
    <x-ui.collection-header title="Habitaciones y camas" subtitle="Explora cada espacio y encuentra la ubicación que necesitas." icon="ph-bed" eyebrow="Administración / Espacios de cuidado" :date="now()->locale('es')">
        <x-slot:actions>
            <button type="button" class="rm-btn-secondary" @click="estadisticas = !estadisticas" :aria-expanded="estadisticas" aria-controls="habitaciones-graficos"><i class="ph-bold ph-chart-bar" aria-hidden="true"></i> <span x-text="estadisticas ? 'Ocultar gráficos' : 'Mostrar gráficos'"></span></button>
            <button class="rm-btn-icon" type="button" @click="actualizar()" :disabled="loading" aria-label="Actualizar habitaciones"><i class="ph-bold ph-arrow-clockwise" aria-hidden="true"></i></button>
            @can('habitaciones.gestionar')<a href="{{ route('admin.habitaciones.index') }}" class="rm-btn-secondary"><i class="ph-bold ph-gear-six" aria-hidden="true"></i> Gestionar espacios</a>@endcan
        </x-slot:actions>
    </x-ui.collection-header>

    <section class="rm-residents-overview" aria-label="Disponibilidad física de camas">
        @foreach($estados as $clave => [$nombre, $icono, $explicacion])
        <a wire:navigate href="{{ $enlace(['disponibilidad' => ($filtros['disponibilidad'] ?? '') === $clave ? null : $clave, 'estado' => null]) }}" class="rm-residents-metric rm-building-metric is-{{ $clave }} {{ ($filtros['disponibilidad'] ?? '') === $clave ? 'is-active' : '' }}" @if(($filtros['disponibilidad'] ?? '') === $clave) aria-current="page" @endif><span><i class="ph-bold {{ $icono }}" aria-hidden="true"></i></span><div><strong>{{ $resumen[$clave] }}</strong><h2>{{ $nombre }}s</h2><p>{{ $explicacion }}</p></div><i class="ph-bold ph-arrow-up-right" aria-hidden="true"></i></a>
        @endforeach
    </section>
    <section id="habitaciones-graficos" class="rm-residents-analytics" x-show="estadisticas" x-transition.opacity aria-label="Gráficos de ocupación">
        <article class="rm-residents-chart"><header><h2><i class="ph-bold ph-chart-donut" aria-hidden="true"></i> Ocupación del espacio</h2><p>{{ $resumen['total'] }} camas registradas para la búsqueda y ubicación elegidas</p></header><div class="rm-residents-chart__content"><div class="rm-residents-donut" role="img" aria-label="{{ $porcentaje }} por ciento de camas ocupadas"><svg viewBox="0 0 120 120" aria-hidden="true"><circle class="rm-residents-donut__track" cx="60" cy="60" r="48"/><circle class="rm-building-donut" cx="60" cy="60" r="48" pathLength="100" stroke-dasharray="{{ $porcentaje }} 100"/></svg><span><strong>{{ $porcentaje }}%</strong><small>ocupación física</small></span></div><div class="rm-residents-legend">@foreach($estados as $clave => [$nombre, $icono])<a wire:navigate class="is-{{ $clave }}" href="{{ $enlace(['disponibilidad' => $clave, 'estado' => null]) }}"><i class="ph-bold {{ $icono }}" aria-hidden="true"></i><span>{{ $nombre }}</span><strong>{{ $resumen[$clave] }}</strong></a>@endforeach</div></div></article>
        <article class="rm-residents-chart"><header><h2><i class="ph-bold ph-buildings" aria-hidden="true"></i> Espacios por piso</h2><p>Ocupadas y disponibles; abre un piso para explorarlo</p></header><div class="rm-building-floor-chart">@forelse($pisos as $planta)<a wire:navigate href="{{ $enlace(['vista' => 'camas', 'piso' => filled($planta->piso) ? $planta->piso : '__sin_piso__', 'cod_habitacion' => null]) }}"><span>{{ filled($planta->piso) ? 'Piso '.$planta->piso : 'Piso sin registrar' }}</span><strong>{{ $planta->ocupadas }} ocupadas · {{ $planta->disponibles }} libres</strong><div aria-hidden="true"><span class="is-ocupado" style="width: {{ $planta->total ? $planta->ocupadas / $planta->total * 100 : 0 }}%"></span><span class="is-disponible" style="width: {{ $planta->total ? $planta->disponibles / $planta->total * 100 : 0 }}%"></span></div><small>{{ $planta->total }} camas físicas</small></a>@empty<p>Sin camas que coincidan con esta ubicación o búsqueda.</p>@endforelse</div></article>
    </section>

    <form class="rm-filter-bar rm-residents-filters" action="{{ route('admin.administracion.habitaciones') }}" method="GET" x-ref="filtros" @submit.prevent="filtrar()" role="search" aria-label="Filtrar habitaciones y camas">
        <input type="hidden" name="vista" value="{{ $vista }}"><input type="hidden" name="por_pagina" value="{{ $porPagina }}">
        <div class="rm-residents-search"><label for="espacios-search">Buscar cama, habitación{{ $verPersonas ? ' o residente' : '' }}</label><div><i class="ph-bold ph-magnifying-glass" aria-hidden="true"></i><input id="espacios-search" name="search" type="search" maxlength="100" value="{{ $filtros['search'] ?? '' }}" placeholder="Código, nombre o tipo de cama"></div></div>
        <div class="rm-residents-filter-grid">
            <div><label for="espacios-piso">Piso</label><x-ui.selector id="espacios-piso" name="piso" label="Piso"><option value="">Todos los pisos</option><option value="__sin_piso__" @selected(($filtros['piso'] ?? '') === '__sin_piso__')>Piso sin registrar</option>@foreach($pisosCatalogo as $piso)<option value="{{ $piso }}" @selected(($filtros['piso'] ?? '') === $piso)>Piso {{ $piso }}</option>@endforeach</x-ui.selector></div>
            <div><label for="espacios-habitacion">Habitación</label><x-ui.selector id="espacios-habitacion" name="cod_habitacion" label="Habitación"><option value="">Todas las habitaciones</option>@foreach($habitacionesCatalogo as $hab)<option value="{{ $hab->cod_habitacion }}" @selected(($filtros['cod_habitacion'] ?? '') === $hab->cod_habitacion)>{{ $hab->codigo }}{{ filled($hab->piso) ? ' · '.$hab->piso : '' }}</option>@endforeach</x-ui.selector></div>
            <div><label for="espacios-disponibilidad">Disponibilidad</label><x-ui.selector id="espacios-disponibilidad" name="disponibilidad" label="Disponibilidad"><option value="">Todas las camas</option>@foreach($estados as $clave => [$nombre])<option value="{{ $clave }}" @selected(($filtros['disponibilidad'] ?? '') === $clave)>{{ $nombre }}</option>@endforeach</x-ui.selector></div>
            <div><label for="espacios-estado">Estado registrado</label><x-ui.selector id="espacios-estado" name="estado" label="Estado registrado"><option value="">Todos los estados</option>@foreach($estadosCama as $estado)<option value="{{ $estado }}" @selected(($filtros['estado'] ?? '') === $estado)>{{ str_replace('_', ' ', $estado) }}</option>@endforeach</x-ui.selector></div>
        </div>
        <div class="rm-residents-filter-actions"><p><i class="ph-bold ph-cursor-click" aria-hidden="true"></i> Acércate para una vista previa; selecciona para ver el detalle.</p><button class="rm-btn-primary" type="submit" :disabled="loading"><i class="ph-bold ph-magnifying-glass" aria-hidden="true"></i><span x-text="loading ? 'Buscando…' : 'Buscar'"></span></button>@if($filtrosActivos->isNotEmpty())<a wire:navigate class="rm-btn-secondary" href="{{ route('admin.administracion.habitaciones', ['vista' => $vista, 'por_pagina' => $porPagina]) }}"><i class="ph-bold ph-arrow-counter-clockwise" aria-hidden="true"></i> Limpiar</a>@endif</div>
        @if($filtrosActivos->isNotEmpty())<div class="rm-residents-active" aria-label="Filtros activos"><span>Filtros activos</span>@foreach($filtrosActivos as $clave => $titulo)@php $valor = match($clave) { 'disponibilidad' => $estados[$filtros[$clave]][0], 'piso' => $filtros[$clave] === '__sin_piso__' ? 'Sin registrar' : $filtros[$clave], 'cod_habitacion' => $habitacionesCatalogo->firstWhere('cod_habitacion', $filtros[$clave])?->codigo ?? $filtros[$clave], default => $filtros[$clave] }; @endphp<a wire:navigate href="{{ $enlace([$clave => null]) }}" aria-label="Quitar filtro {{ $titulo }}"><span>{{ $titulo }}: {{ $valor }}</span><i class="ph-bold ph-x" aria-hidden="true"></i></a>@endforeach</div>@endif
    </form>
    <section class="rm-collection-results" aria-label="Explorador de alojamiento"><header class="rm-residents-results__header"><div><h2><i class="ph-bold ph-house-line" aria-hidden="true"></i> Explora la residencia <span>{{ $paginador->total() }} {{ $vista === 'camas' ? 'habitaciones' : 'camas' }}</span></h2><p>La disponibilidad se determina por la ocupación activa y la habilitación de cama y habitación.</p></div><nav class="rm-view-toggle" aria-label="Vistas de alojamiento">@foreach(['camas' => ['Mapa', 'ph-bed'], 'tarjetas' => ['Tarjetas', 'ph-squares-four'], 'lista' => ['Lista', 'ph-list-bullets'], 'tabla' => ['Tabla', 'ph-table']] as $clave => [$titulo, $icono])<a wire:navigate href="{{ $enlace(['vista' => $clave]) }}" class="rm-view-toggle__btn {{ $vista === $clave ? 'is-active' : '' }}" @if($vista === $clave) aria-current="page" @endif><i class="ph-bold {{ $icono }}" aria-hidden="true"></i>{{ $titulo }}</a>@endforeach</nav></header>
        @if($vista === 'camas')
            <div class="rm-building-map-toolbar"><nav class="rm-residents-floors" aria-label="Pisos de la residencia"><a wire:navigate href="{{ $enlace(['piso' => null, 'cod_habitacion' => null]) }}" @if(!filled($filtros['piso'] ?? '')) aria-current="page" @endif>Todos los pisos</a>@foreach($pisosCatalogo as $piso)<a wire:navigate href="{{ $enlace(['piso' => $piso, 'cod_habitacion' => null]) }}" @if(($filtros['piso'] ?? '') === $piso) aria-current="page" @endif>Piso {{ $piso }}</a>@endforeach</nav><button type="button" class="rm-btn-secondary" @click="colapsar = !colapsar" :aria-expanded="!colapsar"><i class="ph-bold ph-arrows-in-line-vertical" aria-hidden="true"></i><span x-text="colapsar ? 'Desplegar todo' : 'Contraer todo'"></span></button></div>
            @foreach($habitaciones->getCollection()->groupBy(fn ($hab) => $hab->piso ?? '') as $piso => $grupo)
            <section class="rm-building-floor" x-data="{abierto: true}" x-init="$watch('colapsar', valor => abierto = !valor)"><button type="button" class="rm-building-floor__toggle" @click="abierto = !abierto" :aria-expanded="abierto" aria-controls="piso-{{ $loop->index }}"><span><i class="ph-bold ph-buildings" aria-hidden="true"></i><strong>{{ filled($piso) ? 'Piso '.$piso : 'Piso sin registrar' }}</strong><small>{{ $grupo->count() }} habitaciones en esta página</small></span><i class="ph-bold ph-caret-down" :class="{'is-rotated': abierto}" aria-hidden="true"></i></button><div id="piso-{{ $loop->index }}" class="rm-building-rooms" x-show="abierto" x-transition.opacity>
                @foreach($grupo as $hab)<article class="rm-building-room" x-data="{expandida: true}" x-init="$watch('colapsar', valor => expandida = !valor)"><button type="button" class="rm-building-room__toggle" @click="expandida = !expandida" :aria-expanded="expandida" aria-controls="hab-{{ $hab->cod_habitacion }}"><i class="ph-bold ph-door-open" aria-hidden="true"></i><span><strong>{{ $hab->codigo }}</strong><small>{{ $hab->nombre ?: 'Habitación' }} · {{ $hab->camas->count() }} camas visibles / capacidad {{ $hab->capacidad }}</small></span><i class="ph-bold ph-caret-down" :class="{'is-rotated': expandida}" aria-hidden="true"></i></button><div id="hab-{{ $hab->cod_habitacion }}" class="rm-building-room__inside" x-show="expandida" x-transition.opacity><div class="rm-building-room__facts"><span>{{ str_replace('_', ' ', $hab->estado) }}</span><span>{{ $hab->tipo ?: 'Tipo sin registrar' }}</span></div><div class="rm-building-beds">@forelse($hab->camas as $cama)@include('pages.admin.administracion.partials.cama-visual')@empty<p>Sin camas registradas.</p>@endforelse</div></div></article>@endforeach
            </div></section>
            @endforeach
        @elseif($vista === 'tabla')
            <div class="rm-table-scroll"><table class="rm-table"><caption class="sr-only">Disponibilidad, ocupante y características de cada cama</caption><thead><tr><th scope="col">Cama</th><th scope="col">Ubicación</th><th scope="col">Disponibilidad</th><th scope="col">Ocupante</th><th scope="col">Desde</th><th scope="col">Detalle</th></tr></thead><tbody>@foreach($camas as $cama)<tr><td><strong>{{ $cama->codigo }}</strong><small class="block">{{ $cama->tipo ?: 'Tipo sin registrar' }}</small></td><td>{{ $cama->habitacion }}<small class="block">{{ filled($cama->piso) ? 'Piso '.$cama->piso : 'Piso sin registrar' }}</small></td><td><span class="rm-building-status is-{{ $cama->estado_mapa }}"><i class="ph-bold {{ $estados[$cama->estado_mapa][1] }}" aria-hidden="true"></i>{{ $estados[$cama->estado_mapa][0] }}</span></td><td>{{ $cama->ocupante ?: ($cama->estado_mapa === 'ocupado' ? 'Ocupación registrada' : 'Sin ocupación activa') }}</td><td>{{ $cama->fecha_hora_asignacion ? \Carbon\Carbon::parse($cama->fecha_hora_asignacion)->format('d/m/Y H:i') : '—' }}</td><td><a wire:navigate class="rm-btn-secondary" href="{{ $enlace(['cama' => $cama->cod_cama]) }}" aria-label="Ver detalle de cama {{ $cama->codigo }}"><i class="ph-bold ph-arrow-up-right" aria-hidden="true"></i> Detalle</a></td></tr>@endforeach</tbody></table></div>
        @else<div class="rm-building-cards is-{{ $vista }}">@foreach($camas as $cama)@include('pages.admin.administracion.partials.cama-visual')@endforeach</div>
        @endif
        @if($paginador->isEmpty())<div class="rm-residents-empty"><i class="ph-bold ph-bed" aria-hidden="true"></i><h3>{{ $filtrosActivos->isNotEmpty() ? 'Sin espacios que coincidan' : 'Todavía no hay espacios registrados' }}</h3><p>Cambia los filtros o consulta otra ubicación para explorar las camas.</p>@if($filtrosActivos->isNotEmpty())<a wire:navigate href="{{ route('admin.administracion.habitaciones', ['vista' => $vista]) }}" class="rm-btn-secondary">Quitar filtros</a>@endif</div>@endif
        <x-ui.paginacion :paginator="$paginador" mode="url" :per-page="$porPagina" label="{{ $vista === 'camas' ? 'habitaciones' : 'camas' }}" />
    </section>
    <template x-teleport="body"><div class="rm-building-preview" x-ref="previa" x-cloak x-show="vistaPrevia" x-transition.opacity :style="posicion" @mouseenter="conservarVistaPrevia()" @mouseleave="diferirCierrePrevia()" role="status"><i class="ph-bold ph-bed" aria-hidden="true"></i><div><strong x-text="vistaPrevia?.codigo"></strong><span x-text="vistaPrevia?.estado"></span><p x-text="vistaPrevia?.ocupante"></p><small>Selecciona para ver características e historial.</small></div></div></template>
    @if($detalle)@include('pages.admin.administracion.partials.detalle-cama')@endif
</div>
</x-sistema-layout>
