<div class="rm-building-editor">
    @if($modalHabitacion || $modalCama)
    @php $esHabitacion = $modalHabitacion; $editando = $esHabitacion ? $editandoHabitacionId : $editandoCamaId; @endphp
    <x-ui.modal-livewire id="editor-espacio" wire:model="{{ $esHabitacion ? 'modalHabitacion' : 'modalCama' }}" title="{{ $editando ? 'Editar' : 'Registrar' }} {{ $esHabitacion ? 'habitación' : 'cama' }}" subtitle="Capacidad y características físicas de la residencia" max-width="md" close-method="cerrarModales">
        <x-slot:icon><i class="ph-bold {{ $esHabitacion ? 'ph-door-open' : 'ph-bed' }}" aria-hidden="true"></i></x-slot:icon>
        <form id="espacio-formulario" wire:submit="{{ $esHabitacion ? 'guardarHabitacion' : 'guardarCama' }}" class="rm-building-editor__grid">
            @if($habitacionContexto)<p class="rm-alert rm-alert--info col-span-full">Habitación {{ $habitacionContexto->codigo }} · {{ $habitacionContexto->camas_count }} camas / capacidad {{ $habitacionContexto->capacidad }}.</p>@endif
            <div><label for="espacio-codigo" class="rm-label">Referencia <span aria-hidden="true">*</span></label><input id="espacio-codigo" class="rm-input" wire:model="codigo" maxlength="30" required placeholder="{{ $esHabitacion ? 'HAB-201' : 'CAM-201-A' }}" aria-invalid="{{ $errors->has('codigo') ? 'true' : 'false' }}" aria-describedby="espacio-codigo-error">@error('codigo')<p id="espacio-codigo-error" class="rm-field-error" role="alert">{{ $message }}</p>@enderror</div>
            @if($esHabitacion)<div><label for="espacio-nombre" class="rm-label">Nombre visible</label><input id="espacio-nombre" class="rm-input" wire:model="nombre" maxlength="80">@error('nombre')<p class="rm-field-error" role="alert">{{ $message }}</p>@enderror</div>@endif
            <div><label for="espacio-tipo" class="rm-label">Tipo {{ $esHabitacion ? 'de habitación' : 'de cama' }}</label><input id="espacio-tipo" class="rm-input" wire:model="tipo" maxlength="40" placeholder="{{ $esHabitacion ? 'Individual, compartida…' : 'Articulada, estándar…' }}">@error('tipo')<p class="rm-field-error" role="alert">{{ $message }}</p>@enderror</div>
            @if($esHabitacion)<div><label for="espacio-piso" class="rm-label">Piso registrado</label><input id="espacio-piso" class="rm-input" wire:model="piso" maxlength="30" placeholder="Identificación del piso">@error('piso')<p class="rm-field-error" role="alert">{{ $message }}</p>@enderror</div><div><label for="espacio-capacidad" class="rm-label">Capacidad física <span aria-hidden="true">*</span></label><input id="espacio-capacidad" class="rm-input" type="number" min="1" max="50" wire:model="capacidad" required>@error('capacidad')<p class="rm-field-error" role="alert">{{ $message }}</p>@enderror</div>@endif
            <div><label for="espacio-estado" class="rm-label">Estado físico <span aria-hidden="true">*</span></label><x-ui.selector id="espacio-estado" label="Estado físico" wire:model="estado" teleport="#editor-espacio-portales"><option value="ACTIVA">Activa / habilitada</option><option value="ACTIVO">Activo / habilitado</option><option value="DISPONIBLE">Disponible / habilitada</option><option value="MANTENIMIENTO">En mantenimiento</option><option value="BLOQUEADA">Bloqueada</option>@if(!in_array($estado, ['ACTIVA', 'ACTIVO', 'DISPONIBLE', 'MANTENIMIENTO', 'BLOQUEADA'], true))<option value="{{ $estado }}">{{ str_replace('_', ' ', $estado) }} · estado actual</option>@endif</x-ui.selector>@error('estado')<p class="rm-field-error" role="alert">{{ $message }}</p>@enderror</div>
            <div class="col-span-full"><label for="espacio-observacion" class="rm-label">Observaciones físicas</label><textarea id="espacio-observacion" class="rm-input" wire:model="observacion" rows="3" maxlength="1000"></textarea>@error('observacion')<p class="rm-field-error" role="alert">{{ $message }}</p>@enderror</div>
            <p class="rm-control-help col-span-full">La ocupación se calcula desde las asignaciones. Registrar una cama no asigna un residente.</p>
        </form>
        <div id="editor-espacio-portales"></div>
        <x-slot:footer><button type="button" class="rm-btn-secondary" wire:click="cerrarModales" wire:loading.attr="disabled">Cancelar</button><button type="submit" form="espacio-formulario" class="rm-btn-primary" wire:loading.attr="disabled"><i class="ph-bold ph-floppy-disk" aria-hidden="true"></i><span wire:loading.remove>Guardar {{ $esHabitacion ? 'habitación' : 'cama' }}</span><span wire:loading>Guardando…</span></button></x-slot:footer>
    </x-ui.modal-livewire>
    @endif
</div>
